### ISSUE TITLE
Existing but checked items are added again, rather than being unchecked

### ISSUE THREAD

**Issue by liamdv4** [kevdliu/hassio-addon-anylist#10]
I have a shopping list in AnyList that I've used for some time. It's full of items that I've added previously and are ticked off each week, e.g. "Apples".

If I ask Assist to "Add apples to the list", it creates a new item so I end up with two entries for Apples, one checked and one unchecked.

Is that expected behaviour or have I done something wrong?

PS Thanks for developing this. I got the add-on running on my RPi 4 by building the docker image from the source. Couldn't get the binary server to work.

**Comment by kevdliu** [comment]
Hello, the addon should be unchecking the existing checked item instead of creating a separate duplicate item. I just tested on my end by checking off an item and then asking assist to add it. The item was unchecked instead of a new one created. Are you using the anylist app / web to check off the item? Do the duplicate items have the exact same spelling and capitalization?

**Comment by liamdv4** [comment]
I've been doing some testing and it seems to depend on how the items are added initially app vs Assist. I need to do more testing but I think it might be caused by the fact that items by Assist have a trailing space. The web/app trims trailing spaces on input so it's not possible to add something with a trailing space that way.

**Comment by kevdliu** [comment]
Ah OK yeah I see the bug now. I just release v1.5.2 of the custom integration (not this addon) that'll trim all trailing whitespace when adding items. It won't fix existing items with trailing spaces but any items added in the future should be fixed.

**Comment by liamdv4** [comment]
That seems to have fixed. Amazingly quick with the update too. Much appreciated!
